### PR TITLE
Fixes for Spinnaker 2.3+

### PR DESCRIPTION
**Pull request by michaelpantic**
Changes for new Spinnaker Versions - trying to merge this so next time I don't have to figure out which branch to use first ;-)
For newer fireflies, apparently Spinnaker 2+ is needed, and the default here was still 1.x something. 

- Some API Changes in the code for 2.2+
- FindSpinnaker.cmake updates for changed default install paths for Spinnaker 2.3+
- Removed auto-downloader, as it did not work anymore, had some passwords hardcoded and downloaded an outdated version
- Removes mavros dependencies that were still in here from the mav team (thanks @clanegge)

### CODE REVIEW

**Comment by michaelpantic** [comment]
@hermannsblum  FYI in case you find something more to add!

**Comment by clanegge** [comment]
LGTM. Do you know if older cameras also work with Spinnaker 2+ or would it make sense to keep an old version on a different branch?

**Comment by michaelpantic** [comment]
> LGTM. Do you know if older cameras also work with Spinnaker 2+ or would it make sense to keep an old version on a different branch?

no idea but I'd guess they are backwards compatible (at least all the ones running on spinnaker anyway)

otherwise people should buy new cameras :-P

**Comment by michaelpantic** [comment]
Tip when installing spinnaker: Only install the actual library and not libspinview etc, as it pulls in QT dependencies that might break things on your system.

To do so, modify the install script (install_spinnaker.sh) to not include any of the spinvideo/spinview packages (on line 38 and following)

**Comment by Jaeyoung-Lim** [comment]
@michaelpantic Thanks! This solved all my problems :smile:

**Pull request merged**
